services:
  - type: web
    name: bincom-laravel-app
    env: docker
    plan: free
    region: frankfurt  # You said your PostgreSQL is hosted in Frankfurt

    dockerfilePath: ./Dockerfile
    buildCommand: ""  # Dockerfile handles install
    startCommand: ""  # CMD is already in Dockerfile

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false

      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-cvtpi815pdvs73dunrag-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: bincomphptest
      - key: DB_USERNAME
        value: bincomphptest_user
      - key: DB_PASSWORD
        value: uz2wFqxX8qu7eXG9S4Xa8UsaxfrxPFXi
